[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"

[build]
  command = "yarn build"
  publish = "dist"
   publish = "site/public"
  command = "hugo"

[context.deploy-preview]
  command = "yarn build:preview"

[dev]
  framework = "hugo"
  targetPort = 3000
   command = "hugo server --watch"
  port = 1313

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true

